-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 12:15:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET latin1 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`acompaniante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`acompaniante` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `clave` VARCHAR(255) NULL DEFAULT NULL,
  `pregunta` VARCHAR(255) NULL DEFAULT NULL,
  `respuesta` VARCHAR(255) NULL DEFAULT NULL,
  `create_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_uniquies_fields` (`email` ASC, `alias` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`pacientes` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(255) NULL DEFAULT NULL,
  `estcivil` VARCHAR(255) NULL DEFAULT NULL,
  `genero` VARCHAR(1) NULL DEFAULT NULL,
  `fnacimiento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `tposangre` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `acompaniante` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_foreign_key_paciente_acompaniante` (`acompaniante` ASC) VISIBLE,
  CONSTRAINT `fk_foreign_key_paciente_acompaniante`
    FOREIGN KEY (`acompaniante`)
    REFERENCES `app`.`acompaniante` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`antfamiliares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`antfamiliares` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `paciente` INT(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_antfamiliares_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_antfamiliares_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`antpersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`antpersonales` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `vsexualactiva` VARCHAR(255) NULL DEFAULT NULL,
  `embarazos` INT(5) NULL DEFAULT NULL,
  `abortos` INT(1) NULL DEFAULT NULL,
  `abusoPsico` INT(5) NULL DEFAULT NULL,
  `abusoFis` INT(5) NULL DEFAULT NULL,
  `abadono` INT(5) NULL DEFAULT NULL,
  `vicios` INT(5) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_antpersonales_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_antpersonales_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`consultas` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `fin` DATETIME NULL DEFAULT NULL,
  `enfactual` VARCHAR(255) NULL DEFAULT NULL,
  `diagnostico` VARCHAR(255) NULL DEFAULT NULL,
  `prescripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  `acompaniante_id` INT(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consultas_pacientes` (`paciente` ASC) VISIBLE,
  INDEX `fk_consultas_acompaniante1_idx` (`acompaniante_id` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_acompaniante1`
    FOREIGN KEY (`acompaniante_id`)
    REFERENCES `app`.`acompaniante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`historial` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fregistro` DATE NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `paciente` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `paciente` (`paciente` ASC) VISIBLE,
  CONSTRAINT `historial_ibfk_1`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`recomendaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`recomendaciones` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `tareas` VARCHAR(255) NULL DEFAULT NULL,
  `indicaciones` VARCHAR(255) NULL DEFAULT NULL,
  `consultas_id` INT(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recomendaciones_consultas1_idx` (`consultas_id` ASC) VISIBLE,
  CONSTRAINT `fk_recomendaciones_consultas1`
    FOREIGN KEY (`consultas_id`)
    REFERENCES `app`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`sigvitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`sigvitales` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `prearterial` DECIMAL(5,2) NULL DEFAULT NULL,
  `pulso` DECIMAL(5,2) NULL DEFAULT NULL,
  `peso` DECIMAL(5,2) NULL DEFAULT NULL,
  `talla` DECIMAL(5,2) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sigvitales_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_sigvitales_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app`.`telefonos` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `numero` INT(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefonos_paciente` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_telefonos_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
