-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 15:04:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app` ;

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET latin1 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `app`.`pacientes` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(255) NULL DEFAULT NULL,
  `estcivil` VARCHAR(255) NULL DEFAULT NULL,
  `genero` VARCHAR(1) NULL DEFAULT NULL,
  `fnacimiento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `tposangre` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`antfamiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`antfamiliares` ;

CREATE TABLE IF NOT EXISTS `app`.`antfamiliares` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_antfamiliares_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_antfamiliares_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`antpersonales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`antpersonales` ;

CREATE TABLE IF NOT EXISTS `app`.`antpersonales` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `imenarquia` INT(12) NULL DEFAULT NULL,
  `imenopausia` INT(12) NULL DEFAULT NULL,
  `vsexualactiva` VARCHAR(255) NULL DEFAULT NULL,
  `ciclos` INT(5) NULL DEFAULT NULL,
  `gesta` INT(5) NULL DEFAULT NULL,
  `partos` INT(5) NULL DEFAULT NULL,
  `abortos` INT(1) NULL DEFAULT NULL,
  `cesareas` INT(5) NULL DEFAULT NULL,
  `fum` DATE NULL DEFAULT NULL,
  `fup` DATE NULL DEFAULT NULL,
  `hvivos` INT(5) NULL DEFAULT NULL,
  `mpf` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_antpersonales_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_antpersonales_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`acompaniante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`acompaniante` ;

CREATE TABLE IF NOT EXISTS `app`.`acompaniante` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `clave` VARCHAR(255) NULL DEFAULT NULL,
  `pregunta` VARCHAR(255) NULL DEFAULT NULL,
  `respuesta` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_uniquies_fields` (`email` ASC, `alias` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`consultas` ;

CREATE TABLE IF NOT EXISTS `app`.`consultas` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `enfactual` VARCHAR(255) NULL DEFAULT NULL,
  `diagnostico` VARCHAR(255) NULL DEFAULT NULL,
  `prescripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  `acompaniante_id` INT(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consultas_pacientes` (`paciente` ASC) VISIBLE,
  INDEX `fk_consultas_acompaniante1_idx` (`acompaniante_id` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`),
  CONSTRAINT `fk_consultas_acompaniante1`
    FOREIGN KEY (`acompaniante_id`)
    REFERENCES `app`.`acompaniante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`recomendaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`recomendaciones` ;

CREATE TABLE IF NOT EXISTS `app`.`recomendaciones` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `tareas` VARCHAR(255) NULL DEFAULT NULL,
  `indicaciones` VARCHAR(255) NULL DEFAULT NULL,
  `consultas_id` INT(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recomendaciones_consultas1_idx` (`consultas_id` ASC) VISIBLE,
  CONSTRAINT `fk_recomendaciones_consultas1`
    FOREIGN KEY (`consultas_id`)
    REFERENCES `app`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`historial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`historial` ;

CREATE TABLE IF NOT EXISTS `app`.`historial` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fregistro` DATE NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `recomendaciones_id` INT(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historial_recomendaciones1_idx` (`recomendaciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_historial_recomendaciones1`
    FOREIGN KEY (`recomendaciones_id`)
    REFERENCES `app`.`recomendaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`sigvitales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`sigvitales` ;

CREATE TABLE IF NOT EXISTS `app`.`sigvitales` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `prearterial` DECIMAL(5,2) NULL DEFAULT NULL,
  `pulso` DECIMAL(5,2) NULL DEFAULT NULL,
  `peso` DECIMAL(5,2) NULL DEFAULT NULL,
  `talla` DECIMAL(5,2) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sigvitales_pacientes` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_sigvitales_pacientes`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app`.`telefonos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`telefonos` ;

CREATE TABLE IF NOT EXISTS `app`.`telefonos` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `numero` INT(255) NULL DEFAULT NULL,
  `paciente` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefonos_paciente` (`paciente` ASC) VISIBLE,
  CONSTRAINT `fk_telefonos_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `app`.`pacientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
